package bptree

import (
	"fmt"
	"math/big"

	"github.com/consensys/gnark-crypto/ecc/bn254/kzg"
)

// SNARKNodeData is the native-data representation of one B+ tree node
// that will later be converted into a gnark witness.
//
// Nodes are exported in post-order:
//
//	leaves -> internal nodes -> root
//
// Therefore, every child of an internal node appears earlier in the
// Nodes slice than the parent itself.
type SNARKNodeData[K any] struct {
	// Structural information.
	IsLeaf bool
	IsRoot bool

	// ------------------------------------------------------------
	// LEAF DATA
	// ------------------------------------------------------------

	// Original leaf entries.
	//
	// Empty for internal nodes.
	Entries []Entry[K]

	// ------------------------------------------------------------
	// INTERNAL NODE DATA
	// ------------------------------------------------------------

	// Separator keys.
	//
	// Empty for leaves.
	Keys []K

	// Indices into TreeSNARKData.Nodes.
	//
	// For an internal node with:
	//
	//	C0 C1 C2 ...
	//
	// ChildIndices contains the indices of those children in the
	// flattened post-order node array.
	ChildIndices []int

	// Commitments stored by this internal node for its children.
	//
	// Later, the SNARK circuit will enforce:
	//
	//	ChildCommitments[i]
	//	    ==
	//	Nodes[ChildIndices[i]].Commitment
	//
	// Empty for leaves.
	ChildCommitments []kzg.Digest

	// ------------------------------------------------------------
	// POLYNOMIAL DATA
	// ------------------------------------------------------------

	// Values committed by this node's polynomial.
	//
	// Leaf:
	//
	//	mappedValues
	//
	// Internal:
	//
	//	internalMappedValues
	MappedValues []*big.Int

	// Evaluation points associated with MappedValues.
	//
	// Leaf nodes use the GLOBAL evaluation points already assigned
	// by the B+ tree:
	//
	//	Leaf 0: 0,1,2
	//	Leaf 1: 3,4,5
	//	...
	//
	// Internal nodes continue to use LOCAL evaluation points:
	//
	//	0,1,2,...
	EvaluationPoints []uint64

	// ------------------------------------------------------------
	// KZG DATA
	// ------------------------------------------------------------

	// Commitment to this node's polynomial.
	Commitment kzg.Digest

	// One KZG opening proof per mapped value/evaluation point.
	OpeningProofs []kzg.OpeningProof

	// Node-specific KZG verification key.
	//
	// We intentionally export only Vk, not the proving key.
	VerifyingKey kzg.VerifyingKey
}

// TreeSNARKData is the complete native witness description of the
// authenticated B+ tree.
type TreeSNARKData[K any] struct {
	Order int

	// All nodes in post-order.
	Nodes []SNARKNodeData[K]

	// Index of the root in Nodes.
	//
	// Because Nodes is post-order, this should normally be
	// len(Nodes)-1.
	RootIndex int

	// Convenience copy of the root commitment.
	//
	// Eventually this commitment will become a public input to
	// the PLONK circuit.
	RootCommitment kzg.Digest
}

// cloneBigInts creates independent copies of field values so the
// exported SNARK data does not alias mutable *big.Int objects stored
// inside the tree.
func cloneBigIntsForSnark(values []*big.Int) ([]*big.Int, error) {
	out := make([]*big.Int, len(values))

	for i, value := range values {
		if value == nil {
			return nil, fmt.Errorf(
				"mapped value %d is nil",
				i,
			)
		}

		out[i] = new(big.Int).Set(value)
	}

	return out, nil
}

// ExportSNARKData exports the complete committed B+ tree into a
// flattened representation suitable for conversion into a gnark
// witness.
//
// Important:
//
// This function does NOT generate new commitments, new opening proofs,
// or new SRS values.
//
// It exports the exact cryptographic objects already generated by the
// native B+ tree implementation.
func (t *Tree[K, V]) ExportSNARKData() (*TreeSNARKData[K], error) {
	if t.root == nil {
		return nil, fmt.Errorf(
			"cannot export SNARK data from empty tree",
		)
	}

	result := &TreeSNARKData[K]{
		Order: t.order,
		Nodes: make([]SNARKNodeData[K], 0),
	}

	// ------------------------------------------------------------
	// Recursive post-order traversal.
	// ------------------------------------------------------------

	var exportNode func(
		n *node[K, V],
		isRoot bool,
	) (int, error)

	exportNode = func(
		n *node[K, V],
		isRoot bool,
	) (int, error) {

		if n == nil {
			return -1, fmt.Errorf(
				"encountered nil node while exporting SNARK data",
			)
		}

		if n.commitment == nil {
			return -1, fmt.Errorf(
				"node has no KZG commitment; BuildCommitments must run before ExportSNARKData",
			)
		}

		if n.nodeSRS == nil {
			return -1, fmt.Errorf(
				"node has no node-specific KZG SRS",
			)
		}

		// --------------------------------------------------------
		// First export children.
		// --------------------------------------------------------

		childIndices :=
			make([]int, 0, len(n.children))

		if !n.isLeaf {
			for childPosition, child := range n.children {

				childIndex, err :=
					exportNode(
						child,
						false,
					)

				if err != nil {
					return -1, fmt.Errorf(
						"failed exporting child %d: %w",
						childPosition,
						err,
					)
				}

				childIndices =
					append(
						childIndices,
						childIndex,
					)
			}
		}

		// --------------------------------------------------------
		// Create node snapshot.
		// --------------------------------------------------------

		data := SNARKNodeData[K]{
			IsLeaf: n.isLeaf,
			IsRoot: isRoot,

			Commitment: *n.commitment,

			OpeningProofs: append(
				[]kzg.OpeningProof(nil),
				n.openingProofs...,
			),

			VerifyingKey: n.nodeSRS.Vk,

			ChildIndices: childIndices,
		}

		// --------------------------------------------------------
		// Leaf-specific data.
		// --------------------------------------------------------

		if n.isLeaf {
			if len(n.evaluationPoints) !=
				len(n.mappedValues) {

				return -1, fmt.Errorf(
					"leaf has %d mapped values but %d evaluation points",
					len(n.mappedValues),
					len(n.evaluationPoints),
				)
			}

			if len(n.openingProofs) !=
				len(n.mappedValues) {

				return -1, fmt.Errorf(
					"leaf has %d mapped values but %d opening proofs",
					len(n.mappedValues),
					len(n.openingProofs),
				)
			}

			mappedValues, err :=
				cloneBigIntsForSnark(
					n.mappedValues,
				)

			if err != nil {
				return -1, fmt.Errorf(
					"failed copying leaf mapped values: %w",
					err,
				)
			}

			data.Entries =
				append(
					[]Entry[K](nil),
					n.entries...,
				)

			data.MappedValues =
				mappedValues

			data.EvaluationPoints =
				append(
					[]uint64(nil),
					n.evaluationPoints...,
				)

		} else {

			// ----------------------------------------------------
			// Internal-node structural sanity checks.
			// ----------------------------------------------------

			if len(n.children) !=
				len(n.keys)+1 {

				return -1, fmt.Errorf(
					"internal node has %d keys but %d children",
					len(n.keys),
					len(n.children),
				)
			}

			if len(n.childCommitments) !=
				len(n.children) {

				return -1, fmt.Errorf(
					"internal node has %d children but %d child commitments",
					len(n.children),
					len(n.childCommitments),
				)
			}

			if len(n.internalMappedValues) !=
				len(n.keys) {

				return -1, fmt.Errorf(
					"internal node has %d keys but %d mapped values",
					len(n.keys),
					len(n.internalMappedValues),
				)
			}

			if len(n.openingProofs) !=
				len(n.internalMappedValues) {

				return -1, fmt.Errorf(
					"internal node has %d mapped values but %d opening proofs",
					len(n.internalMappedValues),
					len(n.openingProofs),
				)
			}

			// ----------------------------------------------------
			// Copy separator keys.
			// ----------------------------------------------------

			data.Keys =
				append(
					[]K(nil),
					n.keys...,
				)

			// ----------------------------------------------------
			// Copy internal mapped values.
			// ----------------------------------------------------

			mappedValues, err :=
				cloneBigIntsForSnark(
					n.internalMappedValues,
				)

			if err != nil {
				return -1, fmt.Errorf(
					"failed copying internal mapped values: %w",
					err,
				)
			}

			data.MappedValues =
				mappedValues

			// ----------------------------------------------------
			// Internal nodes use LOCAL points:
			//
			// 0,1,2,...
			// ----------------------------------------------------

			data.EvaluationPoints =
				make(
					[]uint64,
					len(n.internalMappedValues),
				)

			for i := range data.EvaluationPoints {

				data.EvaluationPoints[i] =
					uint64(i)
			}

			// ----------------------------------------------------
			// Copy child commitments.
			// ----------------------------------------------------

			data.ChildCommitments =
				make(
					[]kzg.Digest,
					len(n.childCommitments),
				)

			for i, commitment := range n.childCommitments {

				if commitment == nil {
					return -1, fmt.Errorf(
						"internal child commitment %d is nil",
						i,
					)
				}

				data.ChildCommitments[i] =
					*commitment
			}
		}

		// --------------------------------------------------------
		// Append THIS node only after all children.
		// --------------------------------------------------------

		nodeIndex :=
			len(result.Nodes)

		result.Nodes =
			append(
				result.Nodes,
				data,
			)

		return nodeIndex, nil
	}

	rootIndex, err :=
		exportNode(
			t.root,
			true,
		)

	if err != nil {
		return nil, err
	}

	result.RootIndex =
		rootIndex

	result.RootCommitment =
		*t.root.commitment

	return result, nil
}
